# Generated by Django 5.0.4 on 2026-04-17 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('session_type', models.CharField(choices=[('air', 'Air Conduction'), ('bone', 'Bone Conduction')], default='air', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('strategy_type', models.CharField(default='traditional', max_length=20)),
                ('has_hearing_loss', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_test_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(250, '250 Hz'), (500, '500 Hz'), (1000, '1000 Hz'), (2000, '2000 Hz'), (4000, '4000 Hz'), (8000, '8000 Hz')])),
                ('threshold_db', models.FloatField(blank=True, help_text='Final threshold in dB HL', null=True)),
                ('current_db', models.FloatField(default=40.0, help_text='Current test level in dB HL')),
                ('is_completed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audio_engine.testsession')),
            ],
            options={
                'ordering': ['frequency'],
                'unique_together': {('session', 'frequency')},
            },
        ),
    ]
